name: Minify
on:
  # only for gh-pages
  push:
    branches:
      - gh-pages
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # type of runner
    runs-on: ubuntu-latest

    steps:
      # Checks-out under $GITHUB_WORKSPACE so job has access
      - uses: actions/checkout@v3

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Minfied files"
          branch: ${{ github.ref }}
